version: "3.9"  # optional since v1.27.0
services:
  deployer:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    tty: true
    links:
      - web
    volumes:
      - ..:/app
      - ./resources/dev_site_enabled:/etc/nginx/sites-enabled
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    tty: true
    ports:
      - "8000:80"
    volumes:
        - ..:/tmp
        - ./resources/prod_site_enabled:/etc/nginx/sites-enabled
  dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    tty: true
    ports:
      - "8888:80"
    volumes:
      - ..:/app
      - ./resources/dev_site_enabled:/etc/nginx/sites-enabled
